version: "3.8"

services:

  php:
    build: .docker/php
    container_name: ${DOCKER_PROJECT_NAME}-php
    ports:
      - "8741:80"
    volumes:
      - ./.docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/html
    restart: always
    networks:
      - dev

  database:
    image: mysql
    container_name: ${DOCKER_PROJECT_NAME}-db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: ${DOCKER_PROJECT_NAME}-phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
    networks:
      - dev

  mailer:
    image: schickling/mailcatcher
    ports: [ 1025, 1080 ]
    networks:
      - dev

networks:
  dev:

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
